---

- name: install rabbitmq-server dependencies (RedHat)
  yum: name="{{ item }}" state=present
  with_items:
    - libselinux-python

- name: add erlang rpm key
  rpm_key:
    key: https://packages.erlang-solutions.com/rpm/erlang_solutions.asc
    state: present
  when: ansible_distribution != "RedHat"

# - name: copy erlang repository
#   copy:
#     src: erlang.repo
#     dest: /etc/yum.repos.d/
#     owner: root
#     group: root
#     mode: 0644
#   when: ansible_distribution != "RedHat"

- name: install erlang
  yum:
    name: erlang
    state: present

- name: install rabbitmq-server {{ rabbitmq_version }} (RedHat)
  yum:
    name: "https://dl.bintray.com/rabbitmq/all/rabbitmq-server/{{ rabbitmq_version }}/rabbitmq-server-{{ rabbitmq_version }}-1.el7.noarch.rpm"
    state: present
  when: rabbitmq_repository_on_satellite is not defined


- name: install rabbitmq-server {{ rabbitmq_version }} (RedHat)
  yum:
    name: "rabbitmq-server-{{ rabbitmq_version }}"
    state: present
  when: rabbitmq_repository_on_satellite is defined


- name: enable rabbitmq-server
  service:
    name: rabbitmq-server
    enabled: yes

- name: customize logrotate rules
  template:
    src: etc/logrotate.d/rabbitmq-server.j2
    dest: /etc/logrotate.d/rabbitmq-server
    owner: root
    group: root
    mode: 0644
