
- name: Install yum-utils
  yum:
    name: yum-utils
    state: present 

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install vim
  yum:
    name: vim
    state: present