---
- name: Change rabbitmq erlang cookie
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
    owner: rabbitmq
    group: rabbitmq
    mode: 0400

- name: stop rabbitmq app
  command: rabbitmqctl stop_app

- name: add this node to cluster
  command: rabbitmqctl join_cluster rabbit@192.168.1.2
  when: inventory_hostname != "master"

- name: start rabbitmq app
  command: rabbitmqctl start_app