---

- name: Install wget
  yum: 
    name: wget
    state: present

- name: Install erlang
    shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash"
    args:
      executable: /bin/bash

- name: Install rabbitmq
    shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash"
      args:
        executable: /bin/bash