---

- name: Add rabbitmq repository
  shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash"
  args:
    executable: /bin/bash

- name: Install rabbitmq
  yum: 
    name: rabbitmq-server
    state: present

- name: Stop rabbitmq-server
  systemd: 
    name: rabbitmq-server
    state: stoped

- include_tasks: web_management.yml

- include_tasks: config_cluster.yml

- include_tasks: enable_ha.yml
  when: inventory_hostname == "master"

- name: Enable rabbitmq-server
  systemd: 
    name: rabbitmq-server
    state: started
    enabled: yes

