---

# rabbitmq_cluster_master: 192.168.0.2

# TODO: Change to get_url
- name: Add erlang repository
  shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash"
  args:
    executable: /bin/bash

# TODO: Change to get_url
- name: Add rabbitmq repository
  shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash"
  args:
    executable: /bin/bash

- name: Install rabbitmq
  yum: 
    name: rabbitmq-server
    state: present

- include_tasks: config_cluster.yml

- name: Start and enable rabbitmq-server
  service:
    name: rabbitmq-server
    enabled: yes
    state: started

- include_tasks: cluster.yml

- include_tasks: web_management.yml

- include_tasks: enable_ha.yml

- meta: flush_handlers
