---

# TODO: Change to get_url
- name: Add erlang repository
  shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash"
  args:
    executable: /bin/bash

# TODO: Change to get_url
- name: Add rabbitmq repository
  shell: "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash"
  args:
    executable: /bin/bash

- name: Install rabbitmq
  yum: 
    name: rabbitmq-server
    state: present

- name: Start and enable rabbitmq-server
  systemd: 
    name: rabbitmq-server
    state: started
    daemon_reload: yes

- name: make sure rabbitmq app is up
  command: rabbitmqctl start_app

- include_tasks: config_cluster.yml

- include_tasks: web_management.yml

- include_tasks: enable_ha.yml