---

- name: Enables the rabbitmq_management plugin
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
    
- rabbitmq_user:
    user: alex
    password: alex
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator

# GAMBI
# - name: Enable web management login from outside localhost
#   shell: "echo [{rabbit, [{loopback_users, []}]}]. > /etc/rabbitmq/rabbitmq.config"
#   args:
#     executable: /bin/bash